version: "3.8"

services:
  nginx:
    image: nginx:1.26.3
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
    environment:
      - PROJECT_IMAGE_NAME=${PROJECT_IMAGE_NAME}
    entrypoint: ["/bin/sh", "-c", "envsubst '$$PROJECT_IMAGE_NAME' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"]
    ports:
      - "${HOST_APP_PORT}:80"
    networks:
      - app_network

networks:
  app_network:
    name: ${COMPOSE_PROJECT_NAME}_app_network
    driver: bridge
    external: false
