version: "3.4"
services:
  vue3_quasar_backend:
    image: node:18-alpine
    container_name: vue3_quasar_backend
    entrypoint: /bin/sh
    ports:
      - 3000:3000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ../
        target: /srv/app
    tty: true